source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!

target 'TBCore_Example', :exclusive => true do
  pod 'TBCore', :path => '../'
end

target 'TBCore_Tests', :exclusive => true do
  pod 'TBCore', :path => '../'

  
end
